### PR TITLE
Fix GHA pipeline, install scipy using conda

### PR DESCRIPTION
**Pull request by bittner**
Installing scipy with Pip requires a few prerequisites on the various target platforms. Alternatively, using Conda makes things easier. See [StackOverflow](https://stackoverflow.com/questions/26575587/cant-install-scipy-through-pip) for a related discussion.

This is a follow-up on #602.

### CODE REVIEW

**Comment by bittner** [comment]
Tests against PyPy run fine for all the Python versions. Looks like we can keep them in the setup, what do you think?

Tests that install `scipy` fail only on Windows, because Conda is not put on the `PATH` in GitHub's hosted Windows runners [according to their docs](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#package-management).

@j-towns Any idea how we could fix that easily? Any suggestion on how to proceed?

**Comment by bittner** [comment]
@j-towns The CI/CD setup looks complete now. The Python versions supported by GitHub hosted runners are covered.

Known shortcomings:

- The syntax supported by Pip to install local extras (e.g. `pip install '.[scipy]'`) is not supported by Conda, unfortunately.
- The root-cause for PyPy 3.7 failing to install numpy is not known and addressed (it looks like an infrastructure issue of the GitHub hosted runner).
- Test have not run for macOS yet, likely due to GitHub Actions infrastructure issues.

Other than that this PR is ready to be merged, IMHO.

**Comment by j-towns** [comment]
Looks great, thanks!

**Comment by bittner** [comment]
> Hmm actually I think there is still an issue with SciPy. It looks as though it is being installed globally when it should be, but then [this warning](https://github.com/HIPS/autograd/actions/runs/5714787723/job/15482795148#step:8:62) indicates it is not being found by `import scipy`, and I think that's because it's not being included in the environment that tox sets up. I'm not sure how to fix this.

True. This is most certainly because we're mixing Conda and Pip + virtualenv.

We might try to install `scipy` globally and make sure that shines through in the provisioned virtual environments. IIRC, there is a related [Tox configuration](https://tox.wiki/en/stable/config.html) switch for that.

Trying Conda for everything failed when I tried it during this PR. We might try that again, though, and figure out why Tox didn't like it.

**Pull request merged**
