### PR TITLE
Add jacobian vector product

### PR DESCRIPTION
**Pull request by j-towns**
This would also be useful I think.

### CODE REVIEW

**Comment by duvenaud** [comment]
Awesome, thanks for the contribution!

**Comment by j-towns** [comment]
Has the same functionality as Theano's Rop. Note section 3.1 of [Pearlmutter 2015](http://arxiv.org/pdf/1502.05767v2.pdf), the jacobian vector product could be calculated more efficiently using a single pass of forward mode AD. At the moment we require a forward and a backward pass, which is slower, but not disastrously so.

Do you have plans to implement forward mode AD? Efficient computation of these directional derivatives is the only advantage I'm aware of. Speeding up of hessian-vector products would be very useful for our work.

**Comment by j-towns** [comment]
I think actually that what I've implemented is equivalent to Theano's Lop — that is it left multiplies the jacobian by a vector. Therefore it is not doing the same thing as what is described in Pearlmutter section 3.1. Have made a new commit which reflects this. 

Note this isn't an issue for the hessian because the hessian is symmetric. I don't know if there is a nice way to compute Jv using reverse mode autodiff.

**Comment by mattjj** [comment]
I think we forgot to merge this :) thanks again for the contribution!

**Pull request merged**
