### PR TITLE
Implement VJPs for incomplete gamma functions

### PR DESCRIPTION
**Pull request by gcampanella**
This PR implements VJPs for the regularized lower and upper incomplete gamma functions w.r.t. the limit of integration (`x` in SciPy).

### CODE REVIEW

**Comment by gcampanella** [comment]
Tests fail with the following error:
```
FAIL: test_scipy.test_logit
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/home/travis/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
 self.test(*self.arg)
 File "/home/travis/build/HIPS/autograd/tests/test_scipy.py", line 180, in test_logit
 def test_logit(): unary_ufunc_check(special.logit, lims=[0.05, 0.95], test_complex=False)
 File "/home/travis/build/HIPS/autograd/tests/numpy_utils.py", line 81, in unary_ufunc_check
 combo_check(fun, (0,), [scalar_int, scalar, vector, mat, mat2])
 File "/home/travis/build/HIPS/autograd/tests/numpy_utils.py", line 20, in combo_check
 check_fun_and_grads(fun, cur_args, cur_kwargs, argnums=argnums)
 File "/home/travis/build/HIPS/autograd/tests/numpy_utils.py", line 53, in check_fun_and_grads
 check_grads(d_scalar_fun, *wrt_args)
 File "/home/travis/build/HIPS/autograd/autograd/util.py", line 56, in check_grads
 check_equivalent(exact, numeric)
 File "/home/travis/build/HIPS/autograd/autograd/util.py", line 48, in check_equivalent
 A_flat - B_flat, A_flat, B_flat)
AssertionError: Diffs are:
[ 1.27372599e-05 -3.44125387e-04].
analytic is:
[-0.79472448 0.4953871 ].
numeric is:
[-0.79473722 0.49573122].
-------------------- >> begin captured stdout << ---------------------
. . Second derivative test failed! Args were (array([ 0.78742255, 0.11280738]),) {}
--------------------- >> end captured stdout << ----------------------
```
I'm not sure why the `logit` function (which I haven't modified in this PR) is failing here, whilst `master` passes all tests. Will investigate and report back.

**Comment by mattjj** [comment]
It looks just numerical. Maybe the tests on master were just luckier with their random numbers.

Is there a way to put the test in a more numerically favorable regime (by changing the numerical arguments of the function), or adjusting the tolerance of the equality check?

**Comment by gcampanella** [comment]
You're absolutely right @mattjj, tweaking `lims` in `test_logit` fixes the problem. I've just pushed the change as part of this PR.

As far as I can tell, tolerances are set globally in `util.py`, so I'm wary of modifying them there. Might be worth implementing per-function tolerances to deal with unstable second derivatives, though.

**Comment by mattjj** [comment]
Good idea re: per-function tolerances.

Awesome work, thanks!

**Pull request merged**
