### PR TITLE
Added `erf` and `erfc` to `scipy.special`

### PR DESCRIPTION
**Pull request by dhirschfeld**

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks!

Is it better to write the constant `inv_root_pi = 0.56418958354775627928` in the code instead of just writing `1./np.sqrt(np.pi)`?

**Comment by dhirschfeld** [comment]
IIUC a `sqrt` is a relatively expensive operation so instead of computing it every single time you call the gradient I tend to factor out such constants, especially where they're reusable.

I try not to go overboard though as it can rapidly make your code unintelligible, also without benchmarking it might be a redundant micro-optimisation
```python
In [2]: f = lambda x: 2.*np.exp(-x**2)/np.sqrt(np.pi)

In [3]: g = lambda x: 2.*inv_root_pi*np.exp(-x**2)

In [4]: %timeit f(3.14)
The slowest run took 14.95 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 2.83 µs per loop

In [5]: %timeit g(3.14)
The slowest run took 15.00 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.65 µs per loop

In [6]: from math import sqrt, pi

In [7]: f = lambda x: 2.*np.exp(-x**2)/sqrt(pi)

In [8]: %timeit f(3.14)
The slowest run took 23.36 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.89 µs per loop
```
...so the biggest takeaway from above is to not use numpy-vectorized functions for scalar args. For the scalar math functions the benefit in only 15%. Whether or not that's important probably depends on the application.

I'm probably a little obsessive about avoiding redundant calculations/allocations as I'm often pushing python/numpy to its limits to avoid having to drop down into compiled code. Consequently I'm also very interested in issue #47

**Comment by dhirschfeld** [comment]
...and also in-place numpy operations or operations supporting the `out=` parameter. In my application each operation will be allocating an array hundreds of Mb in size so reusing existing memory can provide huge speed-ups.

**Comment by mattjj** [comment]
Ah I see. But maybe we could compute it just once as `1./np.sqrt(np.pi)` once at the module level instead of hardcoding the number.

Supporting real in-place operations is fundamentally hard with reverse-mode autodiff because, as David recently explained to me, you often need most of the intermediate forward values to evaluate the gradients on the backward pass (and you can't just regenerate them in the backward pass, at least not in general, though Dougal and David have a [paper on reversible learning](http://arxiv.org/abs/1502.03492)). The best we could hope for is to allow in-place syntax but collect forward values behind the scenes, discarding ones we don't need to look up on the backward pass.

**Comment by dhirschfeld** [comment]
Yeah, computing it once at the module level would prob be better as it  is self-documenting then - more so than the awkward variable naming :P

I thought it might be difficult to achieve. If it's not going to help with memory utilisation it's probably not so useful to have in-place syntax excepting for completeness' sake.

**Pull request merged**
