### PR TITLE
Add mvn vjp allowsingular optional arg

### PR DESCRIPTION
**Pull request by j-towns**
Fixes https://github.com/HIPS/autograd/issues/201

### CODE REVIEW

**Comment by mattjj** [comment]
If allow_singular is True and the matrix is in fact singular, should we call a different solve (like np.linalg.lstsq)?

**Comment by mattjj** [comment]
I meant: if allow_singular is True, we should probably call something like lstsq (to handle the case where cov is indeed singular).

**Comment by j-towns** [comment]
Yeah I think so. I'll do that and add some tests for the different cases to
make sure we're calculating the right thing.

**Comment by j-towns** [comment]
OK that's done.

I also discovered a couple of typos in the tests, [here](https://github.com/HIPS/autograd/blob/master/tests/test_scipy.py#L43) and [here](https://github.com/HIPS/autograd/blob/master/tests/test_scipy.py#L47) which meant that the pdf of the mvn wasn't being tested and was incorrect (at least in the broadcasting case). So I've fixed that too.

**Comment by mattjj** [comment]
This is fantastic, nice catch!

**Comment by mattjj** [comment]
Was there a particular reason you chose to use `lambda A, x: np.dot(np.linalg.pinv(A), x)` over `np.linalg.lstsq`? I think `lstsq` may have better broadcasting properties, and it also may be faster (fewer temporaries allocated, fewer ops) and more numerically stable.

**Comment by mattjj** [comment]
I was wrong about the broadcasting; looks like `lstsq` doesn't follow the numpy conventions.

**Comment by mattjj** [comment]
Oh man, and `lstsq` returns a tuple with an int inside it! Never mind, I get it now.

**Pull request merged**
