### PR TITLE
Add numpy.lib.pad, numpy.copy and numpy.compat

### PR DESCRIPTION
**Pull request by yukoba**
I added `numpy.lib.pad()`.
I also added `numpy.copy()` and `numpy.compat` because they are needed for `pad()`.

I copied and modified arraypad.py from NumPy.
Is it all right to do such a thing?
### Modify 1

I changed from `import numpy as np` to `from autograd.numpy import numpy_wrapper as np`.
### Modify 2

Because of bug https://github.com/HIPS/autograd/issues/138 , I changed like this.

``` diff
-    max_chunk = arr[max_slice].max(axis=axis).reshape(pad_singleton)
+    max_chunk = arr1[max_slice].max(axis=axis).reshape(pad_singleton)
```

and

``` diff
-            newmat = _prepend_max(newmat, pad_before, chunk_before, axis)
-            newmat = _append_max(newmat, pad_after, chunk_after, axis)
+            newmat2 = _prepend_max(newmat, pad_before, chunk_before, axis)
+            newmat = _append_max(newmat2, newmat, pad_after, chunk_after, axis)
```

This should be reverted if https://github.com/HIPS/autograd/issues/138 is fixed.
### Modify 3

Removed `astype(arr.dtype)`. astype is not supported in AutoGrad.
### Modify 4

Because `median` is not implemented in AutoGrad https://github.com/HIPS/autograd/issues/139 , I added this.

``` diff
+    if mode == "median":
+        raise ValueError("%s is not implemented" % mode)
```
## Diff of arraypad.py

``` diff
--- arraypad-orig.py    2016-08-14 03:49:55.057816000 +0900
+++ arraypad.py 2016-08-14 13:45:09.377455600 +0900
@@ -3,9 +3,14 @@
 of an n-dimensional array.

 """
+###############################################################################
+# This code is copied and modified from NumPy 1.11.1
+# https://github.com/numpy/numpy/blob/v1.11.1/numpy/lib/arraypad.py
+###############################################################################
+
 from __future__ import division, absolute_import, print_function

-import numpy as np
+from autograd.numpy import numpy_wrapper as np


 __all__ = ['pad']
@@ -261,7 +266,7 @@
     _round_ifneeded(ramp_arr, arr.dtype)

     # Ramp values will most likely be float, cast them to the same type as arr
-    return np.concatenate((ramp_arr.astype(arr.dtype), arr), axis=axis)
+    return np.concatenate((ramp_arr, arr), axis=axis)


 def _append_ramp(arr, pad_amt, end, axis=-1):
@@ -316,7 +321,7 @@
     _round_ifneeded(ramp_arr, arr.dtype)

     # Ramp values will most likely be float, cast them to the same type as arr
-    return np.concatenate((arr, ramp_arr.astype(arr.dtype)), axis=axis)
+    return np.concatenate((arr, ramp_arr), axis=axis)


 def _prepend_max(arr, pad_amt, num, axis=-1):
@@ -371,7 +376,7 @@
                           axis=axis)


-def _append_max(arr, pad_amt, num, axis=-1):
+def _append_max(arr, arr1, pad_amt, num, axis=-1):
     """
     Pad one `axis` of `arr` with the maximum of the last `num` elements.

@@ -420,7 +425,7 @@
                           for (i, x) in enumerate(arr.shape))

     # Extract slice, calculate max, reshape to add singleton dimension back
-    max_chunk = arr[max_slice].max(axis=axis).reshape(pad_singleton)
+    max_chunk = arr1[max_slice].max(axis=axis).reshape(pad_singleton)

     # Concatenate `arr` with `max_chunk`, extended along `axis` by `pad_amt`
     return np.concatenate((arr, max_chunk.repeat(pad_amt, axis=axis)),
@@ -475,11 +480,11 @@
     _round_ifneeded(mean_chunk, arr.dtype)

     # Concatenate `arr` with `mean_chunk`, extended along `axis` by `pad_amt`
-    return np.concatenate((mean_chunk.repeat(pad_amt, axis).astype(arr.dtype),
+    return np.concatenate((mean_chunk.repeat(pad_amt, axis),
                            arr), axis=axis)


-def _append_mean(arr, pad_amt, num, axis=-1):
+def _append_mean(arr, arr1, pad_amt, num, axis=-1):
     """
     Append `pad_amt` mean values along `axis`.

@@ -528,12 +533,12 @@
                           for (i, x) in enumerate(arr.shape))

     # Extract slice, calculate mean, reshape to add singleton dimension back
-    mean_chunk = arr[mean_slice].mean(axis=axis).reshape(pad_singleton)
+    mean_chunk = arr1[mean_slice].mean(axis=axis).reshape(pad_singleton)
     _round_ifneeded(mean_chunk, arr.dtype)

     # Concatenate `arr` with `mean_chunk`, extended along `axis` by `pad_amt`
     return np.concatenate(
-        (arr, mean_chunk.repeat(pad_amt, axis).astype(arr.dtype)), axis=axis)
+        (arr, mean_chunk.repeat(pad_amt, axis)), axis=axis)


 def _prepend_med(arr, pad_amt, num, axis=-1):
@@ -585,10 +590,10 @@

     # Concatenate `arr` with `med_chunk`, extended along `axis` by `pad_amt`
     return np.concatenate(
-        (med_chunk.repeat(pad_amt, axis).astype(arr.dtype), arr), axis=axis)
+        (med_chunk.repeat(pad_amt, axis), arr), axis=axis)


-def _append_med(arr, pad_amt, num, axis=-1):
+def _append_med(arr, arr1, pad_amt, num, axis=-1):
     """
     Append `pad_amt` median values along `axis`.

@@ -637,12 +642,12 @@
                           for (i, x) in enumerate(arr.shape))

     # Extract slice, calculate median, reshape to add singleton dimension back
-    med_chunk = np.median(arr[med_slice], axis=axis).reshape(pad_singleton)
+    med_chunk = np.median(arr1[med_slice], axis=axis).reshape(pad_singleton)
     _round_ifneeded(med_chunk, arr.dtype)

     # Concatenate `arr` with `med_chunk`, extended along `axis` by `pad_amt`
     return np.concatenate(
-        (arr, med_chunk.repeat(pad_amt, axis).astype(arr.dtype)), axis=axis)
+        (arr, med_chunk.repeat(pad_amt, axis)), axis=axis)


 def _prepend_min(arr, pad_amt, num, axis=-1):
@@ -697,7 +702,7 @@
                           axis=axis)


-def _append_min(arr, pad_amt, num, axis=-1):
+def _append_min(arr, arr1, pad_amt, num, axis=-1):
     """
     Append `pad_amt` median values along `axis`.

@@ -746,7 +751,7 @@
                           for (i, x) in enumerate(arr.shape))

     # Extract slice, calculate min, reshape to add singleton dimension back
-    min_chunk = arr[min_slice].min(axis=axis).reshape(pad_singleton)
+    min_chunk = arr1[min_slice].min(axis=axis).reshape(pad_singleton)

     # Concatenate `arr` with `min_chunk`, extended along `axis` by `pad_amt`
     return np.concatenate((arr, min_chunk.repeat(pad_amt, axis=axis)),
@@ -1311,6 +1316,8 @@
            [10, 10, 10, 10, 10, 10, 10],
            [10, 10, 10, 10, 10, 10, 10]])
     """
+    if mode == "median":
+        raise ValueError("%s is not implemented" % mode)
     if not np.asarray(pad_width).dtype.kind == 'i':
         raise TypeError('`pad_width` must be of integral type.')

@@ -1407,26 +1414,26 @@
     elif mode == 'maximum':
         for axis, ((pad_before, pad_after), (chunk_before, chunk_after)) \
                 in enumerate(zip(pad_width, kwargs['stat_length'])):
-            newmat = _prepend_max(newmat, pad_before, chunk_before, axis)
-            newmat = _append_max(newmat, pad_after, chunk_after, axis)
+            newmat2 = _prepend_max(newmat, pad_before, chunk_before, axis)
+            newmat = _append_max(newmat2, newmat, pad_after, chunk_after, axis)

     elif mode == 'mean':
         for axis, ((pad_before, pad_after), (chunk_before, chunk_after)) \
                 in enumerate(zip(pad_width, kwargs['stat_length'])):
-            newmat = _prepend_mean(newmat, pad_before, chunk_before, axis)
-            newmat = _append_mean(newmat, pad_after, chunk_after, axis)
+            newmat2 = _prepend_mean(newmat, pad_before, chunk_before, axis)
+            newmat = _append_mean(newmat2, newmat, pad_after, chunk_after, axis)

     elif mode == 'median':
         for axis, ((pad_before, pad_after), (chunk_before, chunk_after)) \
                 in enumerate(zip(pad_width, kwargs['stat_length'])):
-            newmat = _prepend_med(newmat, pad_before, chunk_before, axis)
-            newmat = _append_med(newmat, pad_after, chunk_after, axis)
+            newmat2 = _prepend_med(newmat, pad_before, chunk_before, axis)
+            newmat = _append_med(newmat2, newmat, pad_after, chunk_after, axis)

     elif mode == 'minimum':
         for axis, ((pad_before, pad_after), (chunk_before, chunk_after)) \
                 in enumerate(zip(pad_width, kwargs['stat_length'])):
-            newmat = _prepend_min(newmat, pad_before, chunk_before, axis)
-            newmat = _append_min(newmat, pad_after, chunk_after, axis)
+            newmat2 = _prepend_min(newmat, pad_before, chunk_before, axis)
+            newmat = _append_min(newmat2, newmat, pad_after, chunk_after, axis)

     elif mode == 'reflect':
         for axis, (pad_before, pad_after) in enumerate(pad_width):
```

### CODE REVIEW

**Comment by yukoba** [comment]
I merged https://github.com/HIPS/autograd/pull/141 to this pull request.
So I do not need "Modify 2" now.

Diff of arraypad.py become this.
```patch
--- arraypad-orig.py	2016-08-14 03:49:55.057816000 +0900
+++ arraypad.py	2016-08-15 22:03:14.920104400 +0900
@@ -3,9 +3,14 @@
 of an n-dimensional array.
 
 """
+###############################################################################
+# This code is copied and modified from NumPy 1.11.1
+# https://github.com/numpy/numpy/blob/v1.11.1/numpy/lib/arraypad.py
+###############################################################################
+
 from __future__ import division, absolute_import, print_function
 
-import numpy as np
+from autograd.numpy import numpy_wrapper as np
 
 
 __all__ = ['pad']
@@ -261,7 +266,7 @@
     _round_ifneeded(ramp_arr, arr.dtype)
 
     # Ramp values will most likely be float, cast them to the same type as arr
-    return np.concatenate((ramp_arr.astype(arr.dtype), arr), axis=axis)
+    return np.concatenate((ramp_arr, arr), axis=axis)
 
 
 def _append_ramp(arr, pad_amt, end, axis=-1):
@@ -316,7 +321,7 @@
     _round_ifneeded(ramp_arr, arr.dtype)
 
     # Ramp values will most likely be float, cast them to the same type as arr
-    return np.concatenate((arr, ramp_arr.astype(arr.dtype)), axis=axis)
+    return np.concatenate((arr, ramp_arr), axis=axis)
 
 
 def _prepend_max(arr, pad_amt, num, axis=-1):
@@ -475,7 +480,7 @@
     _round_ifneeded(mean_chunk, arr.dtype)
 
     # Concatenate `arr` with `mean_chunk`, extended along `axis` by `pad_amt`
-    return np.concatenate((mean_chunk.repeat(pad_amt, axis).astype(arr.dtype),
+    return np.concatenate((mean_chunk.repeat(pad_amt, axis),
                            arr), axis=axis)
 
 
@@ -533,7 +538,7 @@
 
     # Concatenate `arr` with `mean_chunk`, extended along `axis` by `pad_amt`
     return np.concatenate(
-        (arr, mean_chunk.repeat(pad_amt, axis).astype(arr.dtype)), axis=axis)
+        (arr, mean_chunk.repeat(pad_amt, axis)), axis=axis)
 
 
 def _prepend_med(arr, pad_amt, num, axis=-1):
@@ -585,7 +590,7 @@
 
     # Concatenate `arr` with `med_chunk`, extended along `axis` by `pad_amt`
     return np.concatenate(
-        (med_chunk.repeat(pad_amt, axis).astype(arr.dtype), arr), axis=axis)
+        (med_chunk.repeat(pad_amt, axis), arr), axis=axis)
 
 
 def _append_med(arr, pad_amt, num, axis=-1):
@@ -642,7 +647,7 @@
 
     # Concatenate `arr` with `med_chunk`, extended along `axis` by `pad_amt`
     return np.concatenate(
-        (arr, med_chunk.repeat(pad_amt, axis).astype(arr.dtype)), axis=axis)
+        (arr, med_chunk.repeat(pad_amt, axis)), axis=axis)
 
 
 def _prepend_min(arr, pad_amt, num, axis=-1):
@@ -1311,6 +1316,8 @@
            [10, 10, 10, 10, 10, 10, 10],
            [10, 10, 10, 10, 10, 10, 10]])
     """
+    if mode == "median":
+        raise ValueError("%s is not implemented" % mode)
     if not np.asarray(pad_width).dtype.kind == 'i':
         raise TypeError('`pad_width` must be of integral type.')
 ```

**Comment by yukoba** [comment]
I rebased this pull request to Dougalm's https://github.com/HIPS/autograd/pull/141 .

**Comment by mattjj** [comment]
Copying in all of arraypad.py is a lot of code to duplicate, and I'm not sure about license issues. Do you think it's necessary?

**Comment by yukoba** [comment]
> license issues

- NumPy - New BSD License http://www.numpy.org/license.html
- Autograd - MIT license

I believe a new BSD license source can include in a MIT license source, but I am not sure.
If it is impossible, could you license arraypad.py as a new BSD license?

> a lot of code to duplicate

Sorry, I cannot find other good way.

**Comment by yukoba** [comment]
I solved!

1. I rebased to https://github.com/HIPS/autograd/pull/147
2. Now what I need is only to replace the import statement in lib/array.pad. So I changed it to this code.

```python
import imp

_, pathname, _ = imp.find_module("numpy")
with open(pathname + "/lib/arraypad.py", "rt") as fp:
    src = fp.read()
src = src.replace("import numpy as np", "from autograd.numpy import numpy_wrapper as np")
exec(src, globals(), locals())
```

Now I do not have to worry about the license, and I do not have to copy the source code from NumPy.

**Comment by duvenaud** [comment]
Hmm, interesting strategy!  It makes me nervous, but it does get the job done.  I wonder if we could also get rid of our duplicated code for hstack(), vstack(), and dstack() that way too.

**Comment by yukoba** [comment]
> I wonder if we could also get rid of our duplicated code for hstack(), vstack(), and dstack() that way too.

Maybe also for other numpy.lib and scipy functions which are only using Python.

**Pull request closed without merging**
