### PR TITLE
Fix map() usage on Py3.

### PR DESCRIPTION
**Pull request by anntzer**
`map(...).index()` doesn't work on Py3, just use a list comprehension
instead.

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks! It looks like we don't have good test coverage on this logic. How did you spot this? A linter maybe?

**Comment by mattjj** [comment]
I think I prefer keeping the function, since it abstracts the matching logic and keeps the list comprehension body simple:

```python
matches = [match(key) for key in keys]
```

Still not as nice as using `map` though...

**Comment by anntzer** [comment]
I tried grad'ind a somewhat complicated function and got an exception popping up there.
I think map is nice if your function is already there, but if you have to go through a lambda it's not really much better.

**Comment by anntzer** [comment]
Indeed, you could have found this by using pylint too -- you just need to run with say `--errors-only --disable=undefined-variable` (to avoid it getting confused by numpy/scipy star-imports) and inverse-grepping numpy and scipy (to avoid no-member errors on the two modules).

**Pull request merged**
