### PR TITLE
Simplify grad_and_aux

### PR DESCRIPTION
**Pull request by j-towns**
Figured this trick out whilst writing the code for https://github.com/HIPS/autograd/issues/339.

**TODO:**
- [x] Tests for this operator
- [x] Use `unary_to_nary` decorator

### CODE REVIEW

**Comment by j-towns** [comment]
I guess this is gonna be slower (potentially way slower depending on use case), because [the zeros will be propagated through the vjp of aux](https://github.com/j-towns/autograd/blob/simple-grad-and-aux/autograd/differential_operators.py#L139). This is more motivation to implement a symbolic zero that can be propagated FLO free through linear operators!

**Comment by duvenaud** [comment]
This is nice because it allows higher-order derivatives to flow through aux.  The old implementation silently gives zero derivatives wrt aux, I got bitten by this the other day.

**Comment by j-towns** [comment]
Maybe a more efficient solution could involve a new function in core.py which gives the full value and the vjp of just one output of a multi-output function.

Something like:
```python
def make_vjp_out(fun, x, outnum):
    start_node = VJPNode.new_root(x)
    end_value, end_node =  trace(start_node, fun, x)
    # Assume fun returns a tuple
    def vjp(g): return backward_pass(g, end_node.parents[outnum])  # This isn't quite correct
    return vjp, end_value
```

**Comment by mattjj** [comment]
We'd like to avoid the extra-zeros-propagation that this call to autograd.builtins.tuple will cause, but I think it's better to have a slow-and-always-correct implementation than one that can be wrong in surprising ways. Hopefully we can fix this tupling issue soon.

**Pull request merged**
