### PR TITLE
Simplify dot grad

### PR DESCRIPTION
**Pull request by j-towns**
This started as a response to Dougal's TODO [here](https://github.com/HIPS/autograd/blob/dougal-dev/autograd/numpy/numpy_vjps.py#L297) to ensure the grad of dot didn't depend on the variable differentiated wrt.

I realised that really the vjp of dot is just the adjoint of dot (as it is for all linear operators), and then I remembered the fact that the adjoint of the adjoint is just the original operator, and thought that turning the adjoint into a primitive and explicitly making its derivative equal to dot might improve performance of second and higher order derivatives.

For the n'th derivative the speedup could, I think, be linear in n (since the number of nodes was increasing by some constant amount each time a derivative was taken). Now dot and its adjoints (one for each arg) are closed under differentiation, meaning that effect won't occur. Anyway on the simple benchmarks I wrote:
```
    before     after       ratio
[dougal-dev] [simplify-dot-grad]
First derivatives
-  239.69μs    96.71μs      0.40  bench_numpy_vjps.time_dot_0
-  233.31μs   119.53μs      0.51  bench_numpy_vjps.time_dot_1
Second derivatives
-  300.94μs   135.22μs      0.45  bench_numpy_vjps.time_dot_0_0
-  302.74μs   134.07μs      0.44  bench_numpy_vjps.time_dot_0_1
-  299.35μs   131.23μs      0.44  bench_numpy_vjps.time_dot_0_2
-  522.63μs   219.09μs      0.42  bench_numpy_vjps.time_dot_1_0
-  509.52μs   209.25μs      0.41  bench_numpy_vjps.time_dot_1_2
-  510.89μs   208.79μs      0.41  bench_numpy_vjps.time_dot_1_1
```

I think there's still some scope for tidying up and maybe slightly optimizing what I've written. Also I think it would be worth doing something similar to this for the other linear primitives (some might turn out to be easier than dot).

EDIT: I've just tried the benchmarks on bigger arrays and the effect of these changes seems to be reversed, i.e. everything is a bit slower on this branch than dougal-dev. Need to fix that before merging.

### CODE REVIEW

**Comment by j-towns** [comment]
BTW I think the tests are failing due to the changes in https://github.com/HIPS/autograd/pull/282, not this pr

**Comment by mattjj** [comment]
Making the adjoint functions into primitives is a clever design idea!

**Comment by duvenaud** [comment]
> Also I think it would be worth doing something similar to this for the other linear primitives (some might turn out to be easier than dot).

Once we've annotated which functions are linear in which arguments, could we do this automatically?

**Comment by j-towns** [comment]
@mattjj Yeah I think I should probably adapt what you've done for the tjps. I was indeed avoiding using tensordot because I also think the performance sometimes isn't great. If you have a look at [tensordot's implementiation](https://github.com/numpy/numpy/blob/v1.13.0/numpy/core/numeric.py#L1157-L1340) you can see it bottoms out in a call to dot anyway.

I think the .transpose(...).reshape(...) [here](https://github.com/numpy/numpy/blob/v1.13.0/numpy/core/numeric.py#L1337) and the line below require a and b to be copied, which may explain the poor performance, and it should be possible to avoid that. For ultimate speed we could cythonize these primitives or try to compile them with numba/some other compiler (XLA perhaps?).
>>Also I think it would be worth doing something similar to this for the other linear primitives (some might turn out to be easier than dot).

>Once we've annotated which functions are linear in which arguments, could we do this automatically?

@duvenaud I was wondering about that, but I don't think so. We've got to hand-write these adjoint primitives I think. That's quite a lot of effort and I'm not sure whether the performance improvements are actually worth doing it for all the linear primitives.

**Comment by j-towns** [comment]
@mattjj I've just pushed a commit which uses an adapted version of the tjps, and performance on small array is similar to before, and the slow performance on big arrays seems to be fixed.

On small arrays:
```
    before     after       ratio
  [fb05dad8] [ebbdd550]
-  237.81μs   108.20μs      0.45  bench_numpy_vjps.time_dot_0
-  233.53μs   105.31μs      0.45  bench_numpy_vjps.time_dot_1

-  295.05μs   150.08μs      0.51  bench_numpy_vjps.time_dot_0_0
-  311.63μs   149.46μs      0.48  bench_numpy_vjps.time_dot_0_1
-  295.66μs   150.22μs      0.51  bench_numpy_vjps.time_dot_0_2
-  508.86μs   202.59μs      0.40  bench_numpy_vjps.time_dot_1_0
-  511.45μs   206.98μs      0.40  bench_numpy_vjps.time_dot_1_1
-  507.96μs   200.47μs      0.39  bench_numpy_vjps.time_dot_1_2
```
On big arrays this branch now performs roughly the same as dougal-dev on all the above benchmarks.

**Comment by mattjj** [comment]
This is great! (Btw, what command do you run to make that benchmark table?)

Hopefully @dougalm gets a chance to look at this today and merge it. I feel a bit weird merging into a branch called "dougal-dev", even though it's really become our effective development branch!

**Comment by j-towns** [comment]
`asv continous` does the quick comparison between two commits

**Comment by mattjj** [comment]
I was just looking at the [one failed test](https://travis-ci.org/HIPS/autograd/jobs/271653194) and it looks like it's not #282 like I suspected, but instead it is some kind of dict issue. I think it's that the loops in the test aren't defined to execute in a consistent order, so the numerical diff might not agree with the analytic diff (or with other numerical diffs from different evaluations of the function).

I just pushed a change that I hope will fix it, and then hopefully the tests can go green here too!

**Comment by dougalm** [comment]
Great idea Jamie, nice work!

Let's start working from [rewrite-2017](https://github.com/HIPS/autograd/tree/rewrite-2017) instead of dougal-dev.

**Comment by mattjj** [comment]
@dougalm merged these commits into the [dev-1.2](https://github.com/HIPS/autograd/tree/dev-1.2) branch, but it looks like github didn't resolve the PR. (He probably should have merged these commits into dougal-dev so that the PR would close, then switched to dev-1.2.)

I'm going to close the PR because it's merged into dev-1.2 now.

**Pull request closed without merging**
